name: Backport to Develop

on:
  push:
    branches:
      - master

jobs:
  backport:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Determine Release Version
        id: version
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git submodule foreach 'git config --local credential.helper "store --file=.git/credentials"'

      - name: Backport to Develop
        run: |
          # Crea un Pull Request directamente desde master a develop
          PR_URL=$(curl -X POST \
            -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls" \
            -d "{\"base\":\"develop\",\"head\":\"master\",\"title\":\"Backport to Develop\",\"body\":\"Automated backport from master\"}" \
            | jq -r '.html_url')
          # Extra: Esperar a que GitHub termine de procesar el PR
          sleep 10
          # Acepta los cambios del pr
          gh pr merge $PR_URL --auto --squash
          
        env:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
